### ISSUE TITLE
wayland

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/wiki#79]
See: https://github.com/kisslinux/repo/issues/270

TODO:

- [x] Firefox (VAAPI, etc).
- [x] Setting up wayland (packages, XDG_RUNTIME_DIR).
- [x] List of wayland software. (in progress)
- [ ] Pages for individual software ala @/software.

**Comment by sdsddsd1** [comment]
This are two information collecting resources I know for this kind of issue.
https://github.com/natpen/awesome-wayland
https://arewewaylandyet.com/

**Comment by dylanaraps** [comment]
Yes. I'm already using those as a reference. :)

**Comment by dylanaraps** [comment]
Initial pages are done. Expansion can happen at anytime now. I've laid the ground work.
